### PR TITLE
use turbo for dev

### PR DESCRIPTION
**Pull request by mwickett**
Use [Turbopack](https://nextjs.org/docs/architecture/turbopack) for bundling in local dev.

### CODE REVIEW

**Comment by mwickett** [comment]
@rdotrose Could you check out this PR and try running locally before we merge this? It _should_ work fine, but I'd like to be sure first.

**Comment by rdotrose** [comment]
Sure, I can try that in the morning, ok?

**Comment by rdotrose** [comment]
So, when you say run locally, do you mean for me to try and clone the use-turbo branch and then run it using node? Or to run things using the Vercel preview link?

**Comment by mwickett** [comment]
The first one yeah - checkout the 'mw.use-turbo' branch and then try running 'npm run dev'. If the app runs locally then we're good to go.

**Comment by rdotrose** [comment]
Ok, Devon's just cleaning right now but I'll try and run it when she's all
done.

**Comment by rdotrose** [comment]
So, it looks like I can run it. But, confirm with me that I did this in a
correct way since I still don't know too much about what I'm doing yet.

I couldn't see the branch from VS Code initially, so I pressed the refresh
button in the bottom corner.
[image: image.png]
Then once I got the branch, I pressed refresh one more time... just in case.

Then I ran npm run dev and checked the local host link. It all started up,
but I didn't know if there was anything specific in the app that you wanted
me to look at.

Let me know if that works!

**Comment by mwickett** [comment]
Yerp, that should do it. I merged this, so when you check out `main` again, you'll need to `fetch` to pull in the latest changes to the branch (those changes being what I just merged here from this PR)

CleanShot 2024-07-11 at 16 18 14@2x

**Pull request merged**
